
<?php if(isset($message)){ echo $message;} ?><br/>


<?php if(Session::getInstance()->isLoggedIn()): ?>
<?php
$id = Session::getInstance()->getUser()->id;
$admin = User::user($id);
if($admin->admin === 'admin'){
    echo "Ti si admin i imas ovlasti!";
}
?>
<?php endif;?>
<br />

 <?php if(!Session::getInstance()->isLoggedIn()): ?>    
    <a href="<?php echo App::config("url")."admin/login" ?>">Login</a>
    <a href="<?php echo App::config("url")."admin/registration" ?>">Registration</a>
<?php else: ?>
    <a href="<?php echo App::config("url")."admin/logout" ?>">Logout</a><br />
    <p>Click name for details</p>
     <a href="<?php echo App::config('url') ?>Index/updateUser/<?= Session::getInstance()->getUser()->id ?>">
         <?= Session::getInstance()->getUser()->firstname . " " .Session::getInstance()->getUser()->lastname?></a>

    <?php if (Session::getInstance()->getUser()->image === 'unset'):  ?>
     <img src="<?php echo App::config('url') ?>app/functions/barcode.php?text=<?=Session::getInstance()->getBarcode()?>">
     <?php else: ?>
         <img src="<?=App::config("url").Session::getInstance()->getUser()->image?>">

    <?php endif;?>
<?php endif; ?>


<?php if(Session::getInstance()->isLoggedIn()):?>
<form method="post" action="<?php echo App::config('url') ?>Index/newPost">

    <div class="form-group">
        <label for="content">What's on your mind?</label>
        <input id="content" name="content">
    </div>

    <button type="submit" class="btn btn-primary">Save</button>

</form>

<?php endif; ?>





 <?php foreach ($posts as $post): ?><br /><br />

<?php if(Session::getInstance()->isLoggedIn()):?>
 <?php if($admin->admin === 'admin'): ?>
         <a href="<?php echo App::config('url') ?>admin/hidePost/<?php echo $post->id ?>">HidePost</a>  <?= htmlspecialchars($post->getContent()) ?> </a> <br />
     <?php endif; ?>
     <?php endif; ?>
 <?php if($post->getReport() < 5): ?>
    <p>





     <?php if($post->hidden != 'hidden'):  ?>



        <?php echo $post->date ?>
        <a href="<?php echo App::config('url') ?>Index/view/<?= $post->getId(); ?> ">
            <?= htmlspecialchars($post->getContent()) ?> </a> <br />
            <?php if( Session::getInstance()->isLoggedIn() ): ?>
            <a href="<?php echo App::config('url') ?>admin/like/<?php echo $post->id ?>">Like</a>
             <a href="<?php echo App::config('url') ?>admin/report/<?php echo $post->id ?>">Report post</a>
            <?php endif; ?>
            (<?php echo $post->getLikes() ?> likes)
            (<?php echo $post->getReport() ?> Reports)

    <?php foreach ($post->getComments() as $comment): ?>
                 <?php foreach (Comment::find($comment->id) as $like): ?>
                     <?php
                        if($like->reports < 5){
                            $k = true;
                        } else {
                            $k = false;
                        }

                     ?>
                 <?php endforeach; ?>
             <?php if($k === true): ?>
        <p style="margin-left: 20px;">
            <cite><?= htmlspecialchars($comment->user) ?></cite>

            <?php echo $comment->date ?><br />
            <?php echo $comment->date ?><br />
            <?php echo $comment->content ?>
            <?php foreach (Comment::find($comment->id) as $like): ?>
                <?php echo "(".$like->likes ." "."likes)" ?>
                <?php echo "(".$like->reports ." "."reports)" ?>
            <?php endforeach; ?>

            <?php if( Session::getInstance()->isLoggedIn() ): ?>
                <a href="<?php echo App::config('url') ?>admin/commentlike/<?php echo $comment->id ?>">Like</a>

                <a href="<?php echo App::config('url') ?>admin/reportComment/<?php echo $comment->id ?>">Report </a>

            <?php endif; ?>
            <?php endif; ?>
        </p>
    <hr />
    <?php endforeach; ?>


        <?php if(Session::getInstance()->isLoggedIn()):?>
     <form method="post" action="<?php echo App::config('url') ?>Index/newTag/<?= $post->getId() ?>">

         <div class="form-group">
             <label for="content">put some tag on this Post</label>
             <input id="content" name="content">
         </div>

         <button type="submit" class="btn btn-primary">Save</button>

     </form>
             <?php endif; ?>
         <?php endif; ?>
<?php endif; ?>
<?php endforeach; ?>

<form method="post" action="<?php echo App::config('url') ?>admin/search/<?= $post->getId() ?>">

    <div class="form-group">
        <label for="content">put some tag on this Post</label>
        <input id="content" name="content">
    </div>

    <button type="submit" class="btn btn-primary">Save</button>

</form>

<style>

    *,
    *::before,
    *::after {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        font: normal 16px/1.5 "Helvetica Neue", sans-serif;
        background: #456990;
        color: #fff;
        overflow-x: hidden;
        padding-bottom: 50px;
    }  /* INTRO SECTION
–––––––––––––––––––––––––––––––––––––––––––––––––– */

    .intro {
        background: #F45B69;
        padding: 100px 0;
    }

    .container {
        width: 90%;
        max-width: 1200px;
        margin: 0 auto;
        text-align: center;
    }

    h1 {
        font-size: 2.5rem;
    }


    /* TIMELINE
    –––––––––––––––––––––––––––––––––––––––––––––––––– */

    .timeline ul {
        background: #456990;
        padding: 50px 0;
    }

    .timeline ul li {
        list-style-type: none;
        position: relative;
        width: 6px;
        margin: 0 auto;
        padding-top: 50px;
        background: #fff;
    }

    .timeline ul li::after {
        content: '';
        position: absolute;
        left: 50%;
        bottom: 0;
        transform: translateX(-50%);
        width: 30px;
        height: 30px;
        border-radius: 50%;
        background: inherit;
    }

    .timeline ul li div {
        position: relative;
        bottom: 0;
        width: 400px;
        padding: 15px;
        background: #F45B69;
    }

    .timeline ul li div::before {
        content: '';
        position: absolute;
        bottom: 7px;
        width: 0;
        height: 0;
        border-style: solid;
    }

    .timeline ul li:nth-child(odd) div {
        left: 45px;
    }

    .timeline ul li:nth-child(odd) div::before {
        left: -15px;
        border-width: 8px 16px 8px 0;
        border-color: transparent #F45B69 transparent transparent;
    }

    .timeline ul li:nth-child(even) div {
        left: -439px;
    }

    .timeline ul li:nth-child(even) div::before {
        right: -15px;
        border-width: 8px 0 8px 16px;
        border-color: transparent transparent transparent #F45B69;
    }

    time {
        display: block;
        font-size: 1.2rem;
        font-weight: bold;
        margin-bottom: 8px;
    }


    /* EFFECTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– */

    .timeline ul li::after {
        transition: background .5s ease-in-out;
    }

    .timeline ul li.in-view::after {
        background: #F45B69;
    }

    .timeline ul li div {
        visibility: hidden;
        opacity: 0;
        transition: all .5s ease-in-out;
    }

    .timeline ul li:nth-child(odd) div {
        transform: translate3d(200px, 0, 0);
    }

    .timeline ul li:nth-child(even) div {
        transform: translate3d(-200px, 0, 0);
    }

    .timeline ul li.in-view div {
        transform: none;
        visibility: visible;
        opacity: 1;
    }


    /* GENERAL MEDIA QUERIES
    –––––––––––––––––––––––––––––––––––––––––––––––––– */

    @media screen and (max-width: 900px) {
        .timeline ul li div {
            width: 250px;
        }
        .timeline ul li:nth-child(even) div {
            left: -289px;
            /*250+45-6*/
        }
    }

    @media screen and (max-width: 600px) {
        .timeline ul li {
            margin-left: 20px;
        }
        .timeline ul li div {
            width: calc(100vw - 91px);
        }
        .timeline ul li:nth-child(even) div {
            left: 45px;
        }
        .timeline ul li:nth-child(even) div::before {
            left: -15px;
            border-width: 8px 16px 8px 0;
            border-color: transparent #F45B69 transparent transparent;
        }
    }





